In [4]:
import pandas as pd
notas = pd.read_csv("ratings.csv") #associa o arquivo a notas
notas.head() #mostra as 5 primeiras linhas do arquivo

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931